apiVersion: v1
metadata:
  name: database-secret-config
  labels:
    env: dev
    app: bonita
    stack: db
    client: mysuperclient
data:
  dbname: cG9zdGdyZXM=
  password: U3VwZXJjYWxpc3RpY29leHBpYWxpZG9zbzIwMjEh
  username: Ym9uaXRhYnBt
kind: Secret
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bonita-secret-config
  labels:
    env: dev
    app: bonita
    stack: web
    client: mysuperclient
data:
  pfuser: Ym9uaXRhUEY=
  pfpassword: U3VwZXJjYWxpc3RpY29leHBpYWxpZG9zbzIwMjEh
  teuser: Ym9uaXRhVEU=
  tepassword: U3VwZXJjYWxpc3RpY29leHBpYWxpZG9zbzIwMjEh
type: Opaque