apiVersion: v1
kind: Service
metadata:
  name: bonita-web
  labels: 
    app: bonita
    env: dev
    stack: web
    client: mysuperclient
spec:
  type: NodePort
  selector:
    app: bonita
    env: dev
    stack: web
  ports:
    - nodePort: 30000
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bonita-db
  labels: 
    app: bonita
    env: dev
    stack: db
spec:
  type: ClusterIP
  selector:
    app: bonita
    env: dev
    stack: db
    client: mysuperclient
  ports:
    - port: 5432